// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Price                uint64   `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Ciphertext           string   `protobuf:"bytes,6,opt,name=Ciphertext,proto3" json:"Ciphertext,omitempty"`
	Tradename            string   `protobuf:"bytes,7,opt,name=Tradename,proto3" json:"Tradename,omitempty"`
	Region               string   `protobuf:"bytes,8,opt,name=Region,proto3" json:"Region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Order) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Order) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Order) GetCiphertext() string {
	if m != nil {
		return m.Ciphertext
	}
	return ""
}

func (m *Order) GetTradename() string {
	if m != nil {
		return m.Tradename
	}
	return ""
}

func (m *Order) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type Tx struct {
	Nonce                uint64   `protobuf:"varint,1,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,4,opt,name=To,proto3" json:"To,omitempty"`
	Hash                 string   `protobuf:"bytes,5,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Signature            string   `protobuf:"bytes,6,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Time                 int64    `protobuf:"varint,7,opt,name=Time,proto3" json:"Time,omitempty"`
	Script               string   `protobuf:"bytes,8,opt,name=script,proto3" json:"script,omitempty"`
	Order                *Order   `protobuf:"bytes,9,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (m *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(m, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Tx) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Tx) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Tx) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Tx) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Tx) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Tx) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Tx) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *Tx) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type ResTx struct {
	Txs                  []*Tx    `protobuf:"bytes,1,rep,name=Txs,proto3" json:"Txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResTx) Reset()         { *m = ResTx{} }
func (m *ResTx) String() string { return proto.CompactTextString(m) }
func (*ResTx) ProtoMessage()    {}
func (*ResTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *ResTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResTx.Unmarshal(m, b)
}
func (m *ResTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResTx.Marshal(b, m, deterministic)
}
func (m *ResTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResTx.Merge(m, src)
}
func (m *ResTx) XXX_Size() int {
	return xxx_messageInfo_ResTx.Size(m)
}
func (m *ResTx) XXX_DiscardUnknown() {
	xxx_messageInfo_ResTx.DiscardUnknown(m)
}

var xxx_messageInfo_ResTx proto.InternalMessageInfo

func (m *ResTx) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

type ReqTx struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTx) Reset()         { *m = ReqTx{} }
func (m *ReqTx) String() string { return proto.CompactTextString(m) }
func (*ReqTx) ProtoMessage()    {}
func (*ReqTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *ReqTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTx.Unmarshal(m, b)
}
func (m *ReqTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTx.Marshal(b, m, deterministic)
}
func (m *ReqTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTx.Merge(m, src)
}
func (m *ReqTx) XXX_Size() int {
	return xxx_messageInfo_ReqTx.Size(m)
}
func (m *ReqTx) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTx.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTx proto.InternalMessageInfo

func (m *ReqTx) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ReqTxByHash struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTxByHash) Reset()         { *m = ReqTxByHash{} }
func (m *ReqTxByHash) String() string { return proto.CompactTextString(m) }
func (*ReqTxByHash) ProtoMessage()    {}
func (*ReqTxByHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *ReqTxByHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTxByHash.Unmarshal(m, b)
}
func (m *ReqTxByHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTxByHash.Marshal(b, m, deterministic)
}
func (m *ReqTxByHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTxByHash.Merge(m, src)
}
func (m *ReqTxByHash) XXX_Size() int {
	return xxx_messageInfo_ReqTxByHash.Size(m)
}
func (m *ReqTxByHash) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTxByHash.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTxByHash proto.InternalMessageInfo

func (m *ReqTxByHash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type ReqBalance struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBalance) Reset()         { *m = ReqBalance{} }
func (m *ReqBalance) String() string { return proto.CompactTextString(m) }
func (*ReqBalance) ProtoMessage()    {}
func (*ReqBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *ReqBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBalance.Unmarshal(m, b)
}
func (m *ReqBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBalance.Marshal(b, m, deterministic)
}
func (m *ReqBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBalance.Merge(m, src)
}
func (m *ReqBalance) XXX_Size() int {
	return xxx_messageInfo_ReqBalance.Size(m)
}
func (m *ReqBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBalance.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBalance proto.InternalMessageInfo

func (m *ReqBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ResBalance struct {
	Balnce               uint64   `protobuf:"varint,1,opt,name=balnce,proto3" json:"balnce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResBalance) Reset()         { *m = ResBalance{} }
func (m *ResBalance) String() string { return proto.CompactTextString(m) }
func (*ResBalance) ProtoMessage()    {}
func (*ResBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *ResBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResBalance.Unmarshal(m, b)
}
func (m *ResBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResBalance.Marshal(b, m, deterministic)
}
func (m *ResBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResBalance.Merge(m, src)
}
func (m *ResBalance) XXX_Size() int {
	return xxx_messageInfo_ResBalance.Size(m)
}
func (m *ResBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_ResBalance.DiscardUnknown(m)
}

var xxx_messageInfo_ResBalance proto.InternalMessageInfo

func (m *ResBalance) GetBalnce() uint64 {
	if m != nil {
		return m.Balnce
	}
	return 0
}

type ReqBlockByNumber struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBlockByNumber) Reset()         { *m = ReqBlockByNumber{} }
func (m *ReqBlockByNumber) String() string { return proto.CompactTextString(m) }
func (*ReqBlockByNumber) ProtoMessage()    {}
func (*ReqBlockByNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *ReqBlockByNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBlockByNumber.Unmarshal(m, b)
}
func (m *ReqBlockByNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBlockByNumber.Marshal(b, m, deterministic)
}
func (m *ReqBlockByNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBlockByNumber.Merge(m, src)
}
func (m *ReqBlockByNumber) XXX_Size() int {
	return xxx_messageInfo_ReqBlockByNumber.Size(m)
}
func (m *ReqBlockByNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBlockByNumber.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBlockByNumber proto.InternalMessageInfo

func (m *ReqBlockByNumber) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ReqBlockByHash struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBlockByHash) Reset()         { *m = ReqBlockByHash{} }
func (m *ReqBlockByHash) String() string { return proto.CompactTextString(m) }
func (*ReqBlockByHash) ProtoMessage()    {}
func (*ReqBlockByHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *ReqBlockByHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBlockByHash.Unmarshal(m, b)
}
func (m *ReqBlockByHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBlockByHash.Marshal(b, m, deterministic)
}
func (m *ReqBlockByHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBlockByHash.Merge(m, src)
}
func (m *ReqBlockByHash) XXX_Size() int {
	return xxx_messageInfo_ReqBlockByHash.Size(m)
}
func (m *ReqBlockByHash) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBlockByHash.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBlockByHash proto.InternalMessageInfo

func (m *ReqBlockByHash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type RespBlock struct {
	Height               uint64   `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	PrevBlockHash        string   `protobuf:"bytes,2,opt,name=PrevBlockHash,proto3" json:"PrevBlockHash,omitempty"`
	Txs                  []*Tx    `protobuf:"bytes,3,rep,name=Txs,proto3" json:"Txs,omitempty"`
	Root                 string   `protobuf:"bytes,4,opt,name=Root,proto3" json:"Root,omitempty"`
	Version              uint64   `protobuf:"varint,5,opt,name=Version,proto3" json:"Version,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Hash                 string   `protobuf:"bytes,7,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Miner                string   `protobuf:"bytes,8,opt,name=Miner,proto3" json:"Miner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespBlock) Reset()         { *m = RespBlock{} }
func (m *RespBlock) String() string { return proto.CompactTextString(m) }
func (*RespBlock) ProtoMessage()    {}
func (*RespBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *RespBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespBlock.Unmarshal(m, b)
}
func (m *RespBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespBlock.Marshal(b, m, deterministic)
}
func (m *RespBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespBlock.Merge(m, src)
}
func (m *RespBlock) XXX_Size() int {
	return xxx_messageInfo_RespBlock.Size(m)
}
func (m *RespBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_RespBlock.DiscardUnknown(m)
}

var xxx_messageInfo_RespBlock proto.InternalMessageInfo

func (m *RespBlock) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *RespBlock) GetPrevBlockHash() string {
	if m != nil {
		return m.PrevBlockHash
	}
	return ""
}

func (m *RespBlock) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

func (m *RespBlock) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *RespBlock) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RespBlock) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RespBlock) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *RespBlock) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

type ResposeTxs struct {
	Txs                  []*Tx    `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResposeTxs) Reset()         { *m = ResposeTxs{} }
func (m *ResposeTxs) String() string { return proto.CompactTextString(m) }
func (*ResposeTxs) ProtoMessage()    {}
func (*ResposeTxs) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *ResposeTxs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResposeTxs.Unmarshal(m, b)
}
func (m *ResposeTxs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResposeTxs.Marshal(b, m, deterministic)
}
func (m *ResposeTxs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResposeTxs.Merge(m, src)
}
func (m *ResposeTxs) XXX_Size() int {
	return xxx_messageInfo_ResposeTxs.Size(m)
}
func (m *ResposeTxs) XXX_DiscardUnknown() {
	xxx_messageInfo_ResposeTxs.DiscardUnknown(m)
}

var xxx_messageInfo_ResposeTxs proto.InternalMessageInfo

func (m *ResposeTxs) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

type ResposeNonce struct {
	Nonce                uint64   `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResposeNonce) Reset()         { *m = ResposeNonce{} }
func (m *ResposeNonce) String() string { return proto.CompactTextString(m) }
func (*ResposeNonce) ProtoMessage()    {}
func (*ResposeNonce) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *ResposeNonce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResposeNonce.Unmarshal(m, b)
}
func (m *ResposeNonce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResposeNonce.Marshal(b, m, deterministic)
}
func (m *ResposeNonce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResposeNonce.Merge(m, src)
}
func (m *ResposeNonce) XXX_Size() int {
	return xxx_messageInfo_ResposeNonce.Size(m)
}
func (m *ResposeNonce) XXX_DiscardUnknown() {
	xxx_messageInfo_ResposeNonce.DiscardUnknown(m)
}

var xxx_messageInfo_ResposeNonce proto.InternalMessageInfo

func (m *ResposeNonce) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type ReqNonce struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqNonce) Reset()         { *m = ReqNonce{} }
func (m *ReqNonce) String() string { return proto.CompactTextString(m) }
func (*ReqNonce) ProtoMessage()    {}
func (*ReqNonce) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *ReqNonce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNonce.Unmarshal(m, b)
}
func (m *ReqNonce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNonce.Marshal(b, m, deterministic)
}
func (m *ReqNonce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNonce.Merge(m, src)
}
func (m *ReqNonce) XXX_Size() int {
	return xxx_messageInfo_ReqNonce.Size(m)
}
func (m *ReqNonce) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNonce.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNonce proto.InternalMessageInfo

func (m *ReqNonce) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ReqTransaction struct {
	From                 string   `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Nonce                uint64   `protobuf:"varint,4,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Priv                 string   `protobuf:"bytes,5,opt,name=Priv,proto3" json:"Priv,omitempty"`
	Order                *Order   `protobuf:"bytes,6,opt,name=Order,proto3" json:"Order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTransaction) Reset()         { *m = ReqTransaction{} }
func (m *ReqTransaction) String() string { return proto.CompactTextString(m) }
func (*ReqTransaction) ProtoMessage()    {}
func (*ReqTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *ReqTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTransaction.Unmarshal(m, b)
}
func (m *ReqTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTransaction.Marshal(b, m, deterministic)
}
func (m *ReqTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTransaction.Merge(m, src)
}
func (m *ReqTransaction) XXX_Size() int {
	return xxx_messageInfo_ReqTransaction.Size(m)
}
func (m *ReqTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTransaction proto.InternalMessageInfo

func (m *ReqTransaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ReqTransaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ReqTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqTransaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ReqTransaction) GetPriv() string {
	if m != nil {
		return m.Priv
	}
	return ""
}

func (m *ReqTransaction) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type ResTransaction struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResTransaction) Reset()         { *m = ResTransaction{} }
func (m *ResTransaction) String() string { return proto.CompactTextString(m) }
func (*ResTransaction) ProtoMessage()    {}
func (*ResTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}

func (m *ResTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResTransaction.Unmarshal(m, b)
}
func (m *ResTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResTransaction.Marshal(b, m, deterministic)
}
func (m *ResTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResTransaction.Merge(m, src)
}
func (m *ResTransaction) XXX_Size() int {
	return xxx_messageInfo_ResTransaction.Size(m)
}
func (m *ResTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ResTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ResTransaction proto.InternalMessageInfo

func (m *ResTransaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type ReqLockBalance struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLockBalance) Reset()         { *m = ReqLockBalance{} }
func (m *ReqLockBalance) String() string { return proto.CompactTextString(m) }
func (*ReqLockBalance) ProtoMessage()    {}
func (*ReqLockBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{15}
}

func (m *ReqLockBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLockBalance.Unmarshal(m, b)
}
func (m *ReqLockBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLockBalance.Marshal(b, m, deterministic)
}
func (m *ReqLockBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLockBalance.Merge(m, src)
}
func (m *ReqLockBalance) XXX_Size() int {
	return xxx_messageInfo_ReqLockBalance.Size(m)
}
func (m *ReqLockBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLockBalance.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLockBalance proto.InternalMessageInfo

func (m *ReqLockBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ReqLockBalance) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type RespLockBalance struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespLockBalance) Reset()         { *m = RespLockBalance{} }
func (m *RespLockBalance) String() string { return proto.CompactTextString(m) }
func (*RespLockBalance) ProtoMessage()    {}
func (*RespLockBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{16}
}

func (m *RespLockBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespLockBalance.Unmarshal(m, b)
}
func (m *RespLockBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespLockBalance.Marshal(b, m, deterministic)
}
func (m *RespLockBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespLockBalance.Merge(m, src)
}
func (m *RespLockBalance) XXX_Size() int {
	return xxx_messageInfo_RespLockBalance.Size(m)
}
func (m *RespLockBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_RespLockBalance.DiscardUnknown(m)
}

var xxx_messageInfo_RespLockBalance proto.InternalMessageInfo

func (m *RespLockBalance) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ReqUnlockBalance struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUnlockBalance) Reset()         { *m = ReqUnlockBalance{} }
func (m *ReqUnlockBalance) String() string { return proto.CompactTextString(m) }
func (*ReqUnlockBalance) ProtoMessage()    {}
func (*ReqUnlockBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{17}
}

func (m *ReqUnlockBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUnlockBalance.Unmarshal(m, b)
}
func (m *ReqUnlockBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUnlockBalance.Marshal(b, m, deterministic)
}
func (m *ReqUnlockBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUnlockBalance.Merge(m, src)
}
func (m *ReqUnlockBalance) XXX_Size() int {
	return xxx_messageInfo_ReqUnlockBalance.Size(m)
}
func (m *ReqUnlockBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUnlockBalance.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUnlockBalance proto.InternalMessageInfo

func (m *ReqUnlockBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ReqUnlockBalance) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type RespUnlockBalance struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespUnlockBalance) Reset()         { *m = RespUnlockBalance{} }
func (m *RespUnlockBalance) String() string { return proto.CompactTextString(m) }
func (*RespUnlockBalance) ProtoMessage()    {}
func (*RespUnlockBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{18}
}

func (m *RespUnlockBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespUnlockBalance.Unmarshal(m, b)
}
func (m *RespUnlockBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespUnlockBalance.Marshal(b, m, deterministic)
}
func (m *RespUnlockBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespUnlockBalance.Merge(m, src)
}
func (m *RespUnlockBalance) XXX_Size() int {
	return xxx_messageInfo_RespUnlockBalance.Size(m)
}
func (m *RespUnlockBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_RespUnlockBalance.DiscardUnknown(m)
}

var xxx_messageInfo_RespUnlockBalance proto.InternalMessageInfo

func (m *RespUnlockBalance) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ReqCreateAddr struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateAddr) Reset()         { *m = ReqCreateAddr{} }
func (m *ReqCreateAddr) String() string { return proto.CompactTextString(m) }
func (*ReqCreateAddr) ProtoMessage()    {}
func (*ReqCreateAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{19}
}

func (m *ReqCreateAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateAddr.Unmarshal(m, b)
}
func (m *ReqCreateAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateAddr.Marshal(b, m, deterministic)
}
func (m *ReqCreateAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateAddr.Merge(m, src)
}
func (m *ReqCreateAddr) XXX_Size() int {
	return xxx_messageInfo_ReqCreateAddr.Size(m)
}
func (m *ReqCreateAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateAddr.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateAddr proto.InternalMessageInfo

type RespCreateAddr struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Privkey              string   `protobuf:"bytes,2,opt,name=privkey,proto3" json:"privkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespCreateAddr) Reset()         { *m = RespCreateAddr{} }
func (m *RespCreateAddr) String() string { return proto.CompactTextString(m) }
func (*RespCreateAddr) ProtoMessage()    {}
func (*RespCreateAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{20}
}

func (m *RespCreateAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespCreateAddr.Unmarshal(m, b)
}
func (m *RespCreateAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespCreateAddr.Marshal(b, m, deterministic)
}
func (m *RespCreateAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespCreateAddr.Merge(m, src)
}
func (m *RespCreateAddr) XXX_Size() int {
	return xxx_messageInfo_RespCreateAddr.Size(m)
}
func (m *RespCreateAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_RespCreateAddr.DiscardUnknown(m)
}

var xxx_messageInfo_RespCreateAddr proto.InternalMessageInfo

func (m *RespCreateAddr) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RespCreateAddr) GetPrivkey() string {
	if m != nil {
		return m.Privkey
	}
	return ""
}

type ReqMaxBlockNumber struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMaxBlockNumber) Reset()         { *m = ReqMaxBlockNumber{} }
func (m *ReqMaxBlockNumber) String() string { return proto.CompactTextString(m) }
func (*ReqMaxBlockNumber) ProtoMessage()    {}
func (*ReqMaxBlockNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{21}
}

func (m *ReqMaxBlockNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMaxBlockNumber.Unmarshal(m, b)
}
func (m *ReqMaxBlockNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMaxBlockNumber.Marshal(b, m, deterministic)
}
func (m *ReqMaxBlockNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMaxBlockNumber.Merge(m, src)
}
func (m *ReqMaxBlockNumber) XXX_Size() int {
	return xxx_messageInfo_ReqMaxBlockNumber.Size(m)
}
func (m *ReqMaxBlockNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMaxBlockNumber.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMaxBlockNumber proto.InternalMessageInfo

type RespMaxBlockNumber struct {
	MaxNumber            uint64   `protobuf:"varint,1,opt,name=maxNumber,proto3" json:"maxNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespMaxBlockNumber) Reset()         { *m = RespMaxBlockNumber{} }
func (m *RespMaxBlockNumber) String() string { return proto.CompactTextString(m) }
func (*RespMaxBlockNumber) ProtoMessage()    {}
func (*RespMaxBlockNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{22}
}

func (m *RespMaxBlockNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespMaxBlockNumber.Unmarshal(m, b)
}
func (m *RespMaxBlockNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespMaxBlockNumber.Marshal(b, m, deterministic)
}
func (m *RespMaxBlockNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespMaxBlockNumber.Merge(m, src)
}
func (m *RespMaxBlockNumber) XXX_Size() int {
	return xxx_messageInfo_RespMaxBlockNumber.Size(m)
}
func (m *RespMaxBlockNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_RespMaxBlockNumber.DiscardUnknown(m)
}

var xxx_messageInfo_RespMaxBlockNumber proto.InternalMessageInfo

func (m *RespMaxBlockNumber) GetMaxNumber() uint64 {
	if m != nil {
		return m.MaxNumber
	}
	return 0
}

type ReqAddrByPriv struct {
	Priv                 string   `protobuf:"bytes,1,opt,name=priv,proto3" json:"priv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAddrByPriv) Reset()         { *m = ReqAddrByPriv{} }
func (m *ReqAddrByPriv) String() string { return proto.CompactTextString(m) }
func (*ReqAddrByPriv) ProtoMessage()    {}
func (*ReqAddrByPriv) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{23}
}

func (m *ReqAddrByPriv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAddrByPriv.Unmarshal(m, b)
}
func (m *ReqAddrByPriv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAddrByPriv.Marshal(b, m, deterministic)
}
func (m *ReqAddrByPriv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAddrByPriv.Merge(m, src)
}
func (m *ReqAddrByPriv) XXX_Size() int {
	return xxx_messageInfo_ReqAddrByPriv.Size(m)
}
func (m *ReqAddrByPriv) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAddrByPriv.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAddrByPriv proto.InternalMessageInfo

func (m *ReqAddrByPriv) GetPriv() string {
	if m != nil {
		return m.Priv
	}
	return ""
}

type RespAddrByPriv struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespAddrByPriv) Reset()         { *m = RespAddrByPriv{} }
func (m *RespAddrByPriv) String() string { return proto.CompactTextString(m) }
func (*RespAddrByPriv) ProtoMessage()    {}
func (*RespAddrByPriv) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{24}
}

func (m *RespAddrByPriv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespAddrByPriv.Unmarshal(m, b)
}
func (m *RespAddrByPriv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespAddrByPriv.Marshal(b, m, deterministic)
}
func (m *RespAddrByPriv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespAddrByPriv.Merge(m, src)
}
func (m *RespAddrByPriv) XXX_Size() int {
	return xxx_messageInfo_RespAddrByPriv.Size(m)
}
func (m *RespAddrByPriv) XXX_DiscardUnknown() {
	xxx_messageInfo_RespAddrByPriv.DiscardUnknown(m)
}

var xxx_messageInfo_RespAddrByPriv proto.InternalMessageInfo

func (m *RespAddrByPriv) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type ReqFrozenAssets struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqFrozenAssets) Reset()         { *m = ReqFrozenAssets{} }
func (m *ReqFrozenAssets) String() string { return proto.CompactTextString(m) }
func (*ReqFrozenAssets) ProtoMessage()    {}
func (*ReqFrozenAssets) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{25}
}

func (m *ReqFrozenAssets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqFrozenAssets.Unmarshal(m, b)
}
func (m *ReqFrozenAssets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqFrozenAssets.Marshal(b, m, deterministic)
}
func (m *ReqFrozenAssets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqFrozenAssets.Merge(m, src)
}
func (m *ReqFrozenAssets) XXX_Size() int {
	return xxx_messageInfo_ReqFrozenAssets.Size(m)
}
func (m *ReqFrozenAssets) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqFrozenAssets.DiscardUnknown(m)
}

var xxx_messageInfo_ReqFrozenAssets proto.InternalMessageInfo

func (m *ReqFrozenAssets) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type RespFrozenAssets struct {
	FrozenAssets         uint64   `protobuf:"varint,1,opt,name=frozenAssets,proto3" json:"frozenAssets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespFrozenAssets) Reset()         { *m = RespFrozenAssets{} }
func (m *RespFrozenAssets) String() string { return proto.CompactTextString(m) }
func (*RespFrozenAssets) ProtoMessage()    {}
func (*RespFrozenAssets) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{26}
}

func (m *RespFrozenAssets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespFrozenAssets.Unmarshal(m, b)
}
func (m *RespFrozenAssets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespFrozenAssets.Marshal(b, m, deterministic)
}
func (m *RespFrozenAssets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespFrozenAssets.Merge(m, src)
}
func (m *RespFrozenAssets) XXX_Size() int {
	return xxx_messageInfo_RespFrozenAssets.Size(m)
}
func (m *RespFrozenAssets) XXX_DiscardUnknown() {
	xxx_messageInfo_RespFrozenAssets.DiscardUnknown(m)
}

var xxx_messageInfo_RespFrozenAssets proto.InternalMessageInfo

func (m *RespFrozenAssets) GetFrozenAssets() uint64 {
	if m != nil {
		return m.FrozenAssets
	}
	return 0
}

type ReqSignOrd struct {
	Priv                 string   `protobuf:"bytes,1,opt,name=priv,proto3" json:"priv,omitempty"`
	Order                *Order   `protobuf:"bytes,2,opt,name=Order,proto3" json:"Order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSignOrd) Reset()         { *m = ReqSignOrd{} }
func (m *ReqSignOrd) String() string { return proto.CompactTextString(m) }
func (*ReqSignOrd) ProtoMessage()    {}
func (*ReqSignOrd) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{27}
}

func (m *ReqSignOrd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSignOrd.Unmarshal(m, b)
}
func (m *ReqSignOrd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSignOrd.Marshal(b, m, deterministic)
}
func (m *ReqSignOrd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSignOrd.Merge(m, src)
}
func (m *ReqSignOrd) XXX_Size() int {
	return xxx_messageInfo_ReqSignOrd.Size(m)
}
func (m *ReqSignOrd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSignOrd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSignOrd proto.InternalMessageInfo

func (m *ReqSignOrd) GetPriv() string {
	if m != nil {
		return m.Priv
	}
	return ""
}

func (m *ReqSignOrd) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type RespSignOrd struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSignOrd) Reset()         { *m = RespSignOrd{} }
func (m *RespSignOrd) String() string { return proto.CompactTextString(m) }
func (*RespSignOrd) ProtoMessage()    {}
func (*RespSignOrd) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{28}
}

func (m *RespSignOrd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSignOrd.Unmarshal(m, b)
}
func (m *RespSignOrd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSignOrd.Marshal(b, m, deterministic)
}
func (m *RespSignOrd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSignOrd.Merge(m, src)
}
func (m *RespSignOrd) XXX_Size() int {
	return xxx_messageInfo_RespSignOrd.Size(m)
}
func (m *RespSignOrd) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSignOrd.DiscardUnknown(m)
}

var xxx_messageInfo_RespSignOrd proto.InternalMessageInfo

func (m *RespSignOrd) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *RespSignOrd) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type ReqTokenCreate struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Nonce                uint64   `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Priv                 string   `protobuf:"bytes,5,opt,name=priv,proto3" json:"priv,omitempty"`
	Symbol               string   `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Total                uint64   `protobuf:"varint,7,opt,name=total,proto3" json:"total,omitempty"`
	Fee                  uint64   `protobuf:"varint,8,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTokenCreate) Reset()         { *m = ReqTokenCreate{} }
func (m *ReqTokenCreate) String() string { return proto.CompactTextString(m) }
func (*ReqTokenCreate) ProtoMessage()    {}
func (*ReqTokenCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{29}
}

func (m *ReqTokenCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTokenCreate.Unmarshal(m, b)
}
func (m *ReqTokenCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTokenCreate.Marshal(b, m, deterministic)
}
func (m *ReqTokenCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTokenCreate.Merge(m, src)
}
func (m *ReqTokenCreate) XXX_Size() int {
	return xxx_messageInfo_ReqTokenCreate.Size(m)
}
func (m *ReqTokenCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTokenCreate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTokenCreate proto.InternalMessageInfo

func (m *ReqTokenCreate) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ReqTokenCreate) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ReqTokenCreate) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqTokenCreate) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ReqTokenCreate) GetPriv() string {
	if m != nil {
		return m.Priv
	}
	return ""
}

func (m *ReqTokenCreate) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqTokenCreate) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReqTokenCreate) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

type RespTokenCreate struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespTokenCreate) Reset()         { *m = RespTokenCreate{} }
func (m *RespTokenCreate) String() string { return proto.CompactTextString(m) }
func (*RespTokenCreate) ProtoMessage()    {}
func (*RespTokenCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{30}
}

func (m *RespTokenCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespTokenCreate.Unmarshal(m, b)
}
func (m *RespTokenCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespTokenCreate.Marshal(b, m, deterministic)
}
func (m *RespTokenCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespTokenCreate.Merge(m, src)
}
func (m *RespTokenCreate) XXX_Size() int {
	return xxx_messageInfo_RespTokenCreate.Size(m)
}
func (m *RespTokenCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_RespTokenCreate.DiscardUnknown(m)
}

var xxx_messageInfo_RespTokenCreate proto.InternalMessageInfo

func (m *RespTokenCreate) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type ReqTokenBalance struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTokenBalance) Reset()         { *m = ReqTokenBalance{} }
func (m *ReqTokenBalance) String() string { return proto.CompactTextString(m) }
func (*ReqTokenBalance) ProtoMessage()    {}
func (*ReqTokenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{31}
}

func (m *ReqTokenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTokenBalance.Unmarshal(m, b)
}
func (m *ReqTokenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTokenBalance.Marshal(b, m, deterministic)
}
func (m *ReqTokenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTokenBalance.Merge(m, src)
}
func (m *ReqTokenBalance) XXX_Size() int {
	return xxx_messageInfo_ReqTokenBalance.Size(m)
}
func (m *ReqTokenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTokenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTokenBalance proto.InternalMessageInfo

func (m *ReqTokenBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ReqTokenBalance) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type RespTokenBalance struct {
	Balnce               uint64   `protobuf:"varint,1,opt,name=balnce,proto3" json:"balnce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespTokenBalance) Reset()         { *m = RespTokenBalance{} }
func (m *RespTokenBalance) String() string { return proto.CompactTextString(m) }
func (*RespTokenBalance) ProtoMessage()    {}
func (*RespTokenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{32}
}

func (m *RespTokenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespTokenBalance.Unmarshal(m, b)
}
func (m *RespTokenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespTokenBalance.Marshal(b, m, deterministic)
}
func (m *RespTokenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespTokenBalance.Merge(m, src)
}
func (m *RespTokenBalance) XXX_Size() int {
	return xxx_messageInfo_RespTokenBalance.Size(m)
}
func (m *RespTokenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_RespTokenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_RespTokenBalance proto.InternalMessageInfo

func (m *RespTokenBalance) GetBalnce() uint64 {
	if m != nil {
		return m.Balnce
	}
	return 0
}

type ReqTokenTransaction struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Nonce                uint64   `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Priv                 string   `protobuf:"bytes,5,opt,name=priv,proto3" json:"priv,omitempty"`
	TokenAmount          uint64   `protobuf:"varint,6,opt,name=tokenAmount,proto3" json:"tokenAmount,omitempty"`
	Symbol               string   `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Fee                  uint64   `protobuf:"varint,8,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTokenTransaction) Reset()         { *m = ReqTokenTransaction{} }
func (m *ReqTokenTransaction) String() string { return proto.CompactTextString(m) }
func (*ReqTokenTransaction) ProtoMessage()    {}
func (*ReqTokenTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{33}
}

func (m *ReqTokenTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTokenTransaction.Unmarshal(m, b)
}
func (m *ReqTokenTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTokenTransaction.Marshal(b, m, deterministic)
}
func (m *ReqTokenTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTokenTransaction.Merge(m, src)
}
func (m *ReqTokenTransaction) XXX_Size() int {
	return xxx_messageInfo_ReqTokenTransaction.Size(m)
}
func (m *ReqTokenTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTokenTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTokenTransaction proto.InternalMessageInfo

func (m *ReqTokenTransaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ReqTokenTransaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ReqTokenTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqTokenTransaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ReqTokenTransaction) GetPriv() string {
	if m != nil {
		return m.Priv
	}
	return ""
}

func (m *ReqTokenTransaction) GetTokenAmount() uint64 {
	if m != nil {
		return m.TokenAmount
	}
	return 0
}

func (m *ReqTokenTransaction) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqTokenTransaction) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

type RespTokenTransaction struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespTokenTransaction) Reset()         { *m = RespTokenTransaction{} }
func (m *RespTokenTransaction) String() string { return proto.CompactTextString(m) }
func (*RespTokenTransaction) ProtoMessage()    {}
func (*RespTokenTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{34}
}

func (m *RespTokenTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespTokenTransaction.Unmarshal(m, b)
}
func (m *RespTokenTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespTokenTransaction.Marshal(b, m, deterministic)
}
func (m *RespTokenTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespTokenTransaction.Merge(m, src)
}
func (m *RespTokenTransaction) XXX_Size() int {
	return xxx_messageInfo_RespTokenTransaction.Size(m)
}
func (m *RespTokenTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_RespTokenTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_RespTokenTransaction proto.InternalMessageInfo

func (m *RespTokenTransaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type ReqSignedTransaction struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Nonce                uint64   `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Time                 int64    `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Hash                 []byte   `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature            []byte   `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSignedTransaction) Reset()         { *m = ReqSignedTransaction{} }
func (m *ReqSignedTransaction) String() string { return proto.CompactTextString(m) }
func (*ReqSignedTransaction) ProtoMessage()    {}
func (*ReqSignedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{35}
}

func (m *ReqSignedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSignedTransaction.Unmarshal(m, b)
}
func (m *ReqSignedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSignedTransaction.Marshal(b, m, deterministic)
}
func (m *ReqSignedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSignedTransaction.Merge(m, src)
}
func (m *ReqSignedTransaction) XXX_Size() int {
	return xxx_messageInfo_ReqSignedTransaction.Size(m)
}
func (m *ReqSignedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSignedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSignedTransaction proto.InternalMessageInfo

func (m *ReqSignedTransaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ReqSignedTransaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ReqSignedTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqSignedTransaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ReqSignedTransaction) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ReqSignedTransaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ReqSignedTransaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type RespSignedTransaction struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSignedTransaction) Reset()         { *m = RespSignedTransaction{} }
func (m *RespSignedTransaction) String() string { return proto.CompactTextString(m) }
func (*RespSignedTransaction) ProtoMessage()    {}
func (*RespSignedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{36}
}

func (m *RespSignedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSignedTransaction.Unmarshal(m, b)
}
func (m *RespSignedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSignedTransaction.Marshal(b, m, deterministic)
}
func (m *RespSignedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSignedTransaction.Merge(m, src)
}
func (m *RespSignedTransaction) XXX_Size() int {
	return xxx_messageInfo_RespSignedTransaction.Size(m)
}
func (m *RespSignedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSignedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_RespSignedTransaction proto.InternalMessageInfo

func (m *RespSignedTransaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "message.order")
	proto.RegisterType((*Tx)(nil), "message.Tx")
	proto.RegisterType((*ResTx)(nil), "message.res_tx")
	proto.RegisterType((*ReqTx)(nil), "message.req_tx")
	proto.RegisterType((*ReqTxByHash)(nil), "message.req_tx_by_hash")
	proto.RegisterType((*ReqBalance)(nil), "message.req_balance")
	proto.RegisterType((*ResBalance)(nil), "message.res_balance")
	proto.RegisterType((*ReqBlockByNumber)(nil), "message.req_block_by_number")
	proto.RegisterType((*ReqBlockByHash)(nil), "message.req_block_by_hash")
	proto.RegisterType((*RespBlock)(nil), "message.resp_block")
	proto.RegisterType((*ResposeTxs)(nil), "message.respose_txs")
	proto.RegisterType((*ResposeNonce)(nil), "message.respose_nonce")
	proto.RegisterType((*ReqNonce)(nil), "message.req_nonce")
	proto.RegisterType((*ReqTransaction)(nil), "message.req_transaction")
	proto.RegisterType((*ResTransaction)(nil), "message.res_transaction")
	proto.RegisterType((*ReqLockBalance)(nil), "message.req_lock_balance")
	proto.RegisterType((*RespLockBalance)(nil), "message.resp_lock_balance")
	proto.RegisterType((*ReqUnlockBalance)(nil), "message.req_unlock_balance")
	proto.RegisterType((*RespUnlockBalance)(nil), "message.resp_unlock_balance")
	proto.RegisterType((*ReqCreateAddr)(nil), "message.req_create_addr")
	proto.RegisterType((*RespCreateAddr)(nil), "message.resp_create_addr")
	proto.RegisterType((*ReqMaxBlockNumber)(nil), "message.req_max_block_number")
	proto.RegisterType((*RespMaxBlockNumber)(nil), "message.resp_max_block_number")
	proto.RegisterType((*ReqAddrByPriv)(nil), "message.req_addr_by_priv")
	proto.RegisterType((*RespAddrByPriv)(nil), "message.resp_addr_by_priv")
	proto.RegisterType((*ReqFrozenAssets)(nil), "message.req_frozen_assets")
	proto.RegisterType((*RespFrozenAssets)(nil), "message.resp_frozen_assets")
	proto.RegisterType((*ReqSignOrd)(nil), "message.req_sign_ord")
	proto.RegisterType((*RespSignOrd)(nil), "message.resp_sign_ord")
	proto.RegisterType((*ReqTokenCreate)(nil), "message.req_token_create")
	proto.RegisterType((*RespTokenCreate)(nil), "message.resp_token_create")
	proto.RegisterType((*ReqTokenBalance)(nil), "message.req_token_balance")
	proto.RegisterType((*RespTokenBalance)(nil), "message.resp_token_balance")
	proto.RegisterType((*ReqTokenTransaction)(nil), "message.req_token_transaction")
	proto.RegisterType((*RespTokenTransaction)(nil), "message.resp_token_transaction")
	proto.RegisterType((*ReqSignedTransaction)(nil), "message.req_signed_transaction")
	proto.RegisterType((*RespSignedTransaction)(nil), "message.resp_signed_transaction")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 1391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xcd, 0x6e, 0x1b, 0xb7,
	0x13, 0xd7, 0xea, 0x33, 0x1a, 0x7f, 0x25, 0x8c, 0xe3, 0x6c, 0x36, 0x5f, 0x06, 0x91, 0xfc, 0x63,
	0xe0, 0x9f, 0xe4, 0x90, 0x22, 0x68, 0xd1, 0x9b, 0xed, 0xd4, 0x76, 0x80, 0xc4, 0x09, 0xd6, 0x6a,
	0x4f, 0x05, 0x84, 0xb5, 0x44, 0xdb, 0x8b, 0x58, 0xbb, 0x2a, 0x49, 0x07, 0x52, 0xdf, 0xa5, 0xef,
	0xd0, 0x63, 0x5f, 0xa1, 0xa7, 0xde, 0x7b, 0xe9, 0xa5, 0x0f, 0x52, 0xcc, 0x90, 0xbb, 0x22, 0x57,
	0x52, 0x5a, 0xb4, 0x68, 0x4f, 0xe6, 0x0c, 0x67, 0x7f, 0x9c, 0x8f, 0xdf, 0x70, 0x28, 0xc3, 0xda,
	0x48, 0x28, 0x95, 0x9c, 0x8b, 0xe7, 0x63, 0x99, 0xeb, 0x9c, 0x75, 0xac, 0xc8, 0x7f, 0x09, 0xa0,
	0x95, 0xcb, 0xa1, 0x90, 0x6c, 0x1d, 0xea, 0xaf, 0x87, 0x61, 0xb0, 0x1d, 0xec, 0x74, 0xe3, 0xfa,
	0xeb, 0x21, 0x0b, 0xa1, 0xb3, 0x3b, 0x1c, 0x4a, 0xa1, 0x54, 0x58, 0x27, 0x65, 0x21, 0xb2, 0x4d,
	0x68, 0xbd, 0x97, 0xe9, 0x40, 0x84, 0x8d, 0xed, 0x60, 0xa7, 0x19, 0x1b, 0x81, 0x31, 0x68, 0x1e,
	0x25, 0xea, 0x22, 0x6c, 0x92, 0x31, 0xad, 0xd9, 0x3d, 0xe8, 0x9e, 0xa4, 0xe7, 0x59, 0xa2, 0xaf,
	0xa4, 0x08, 0x5b, 0xb4, 0x31, 0x53, 0xb0, 0x07, 0x00, 0xfb, 0xe9, 0xf8, 0x42, 0x48, 0x2d, 0x26,
	0x3a, 0x6c, 0xd3, 0xb6, 0xa3, 0xc1, 0xaf, 0x7b, 0x32, 0x19, 0x8a, 0x2c, 0x19, 0x89, 0xb0, 0x63,
	0xbe, 0x2e, 0x15, 0x6c, 0x0b, 0xda, 0xb1, 0x38, 0x4f, 0xf3, 0x2c, 0xbc, 0x46, 0x5b, 0x56, 0xe2,
	0xbf, 0x06, 0x50, 0xef, 0x4d, 0xd0, 0xc9, 0xe3, 0x3c, 0x1b, 0x08, 0x8a, 0xa8, 0x19, 0x1b, 0x01,
	0x3f, 0xda, 0x1d, 0xe5, 0x57, 0x99, 0xa6, 0x98, 0x9a, 0xb1, 0x95, 0xd0, 0xf9, 0x03, 0x99, 0x8f,
	0x28, 0xa2, 0x6e, 0x4c, 0x6b, 0x4c, 0x48, 0x2f, 0xb7, 0xe1, 0xd4, 0x7b, 0x79, 0x19, 0x60, 0x6b,
	0x59, 0x80, 0xed, 0x6a, 0x80, 0x0c, 0x9a, 0xbd, 0xd4, 0xfa, 0xde, 0x88, 0x69, 0x8d, 0x1e, 0xa8,
	0x81, 0x4c, 0xc7, 0xba, 0x70, 0xdb, 0x48, 0xec, 0x91, 0xad, 0x43, 0xd8, 0xdd, 0x0e, 0x76, 0x56,
	0x5e, 0xac, 0x3f, 0x2f, 0x0a, 0x46, 0xda, 0xd8, 0x6c, 0xf2, 0x27, 0xd0, 0x96, 0x42, 0xf5, 0xf5,
	0x84, 0xdd, 0x87, 0x46, 0x6f, 0xa2, 0xc2, 0x60, 0xbb, 0xb1, 0xb3, 0xf2, 0x62, 0xa5, 0xb4, 0xee,
	0x4d, 0x62, 0xd4, 0x73, 0x8e, 0x86, 0xdf, 0xa1, 0x61, 0x08, 0x9d, 0xc4, 0xd6, 0xd1, 0x14, 0xb7,
	0x10, 0xf9, 0x23, 0x58, 0x37, 0x36, 0xfd, 0xd3, 0x69, 0xff, 0x02, 0xc3, 0x61, 0xd0, 0xc4, 0xbf,
	0xd6, 0x90, 0xd6, 0xfc, 0x09, 0xac, 0xa0, 0xd5, 0x69, 0x72, 0x99, 0x60, 0x06, 0x97, 0xc3, 0x3d,
	0x46, 0x43, 0x55, 0x1a, 0x6e, 0x41, 0xfb, 0x34, 0xb9, 0x9c, 0x55, 0xc0, 0x4a, 0xfc, 0x19, 0xdc,
	0x24, 0xbc, 0xcb, 0x7c, 0xf0, 0x01, 0x0f, 0xce, 0xae, 0x46, 0xa7, 0x42, 0xa2, 0xf9, 0x85, 0x48,
	0xcf, 0x2f, 0x74, 0x61, 0x6e, 0x24, 0xfe, 0x04, 0x6e, 0x78, 0xe6, 0x4b, 0xfd, 0xfc, 0x2d, 0x00,
	0x90, 0x42, 0x8d, 0x8d, 0x29, 0xe2, 0x1d, 0x79, 0x78, 0x46, 0x62, 0x8f, 0x60, 0xed, 0xbd, 0x14,
	0x1f, 0xf7, 0xd0, 0x88, 0xca, 0x69, 0xc8, 0xed, 0x2b, 0x8b, 0xec, 0x36, 0x16, 0x67, 0x17, 0xcf,
	0x8f, 0xf3, 0x5c, 0x17, 0x5c, 0xc7, 0x35, 0x26, 0xe6, 0x1b, 0x21, 0x15, 0x12, 0xb2, 0x45, 0x27,
	0x16, 0x22, 0xf1, 0x38, 0x1d, 0x09, 0xa5, 0x93, 0xd1, 0x98, 0x48, 0xd2, 0x88, 0x67, 0x8a, 0x92,
	0x56, 0x1d, 0x87, 0x56, 0x9b, 0xd0, 0x7a, 0x9b, 0x66, 0x42, 0x5a, 0x8e, 0x18, 0x81, 0x3f, 0xa5,
	0x04, 0x8f, 0x73, 0x25, 0xfa, 0x7a, 0xa2, 0xd0, 0x47, 0xbd, 0x84, 0x01, 0x7a, 0x82, 0xe5, 0x58,
	0x2b, 0xac, 0x33, 0xe2, 0xfe, 0x26, 0xb4, 0x32, 0xb7, 0x23, 0x48, 0xe0, 0x8f, 0xa1, 0x8b, 0xf9,
	0x35, 0x26, 0xcb, 0x8b, 0xfb, 0x43, 0x00, 0x1b, 0x44, 0x16, 0x99, 0x64, 0x2a, 0x19, 0x68, 0x8c,
	0xab, 0x68, 0x9a, 0x60, 0xae, 0x69, 0xea, 0x65, 0xd3, 0xcc, 0x1a, 0xae, 0xe1, 0x35, 0x5c, 0xd9,
	0x9e, 0x4d, 0xb7, 0x3d, 0x19, 0x34, 0xdf, 0xcb, 0xf4, 0x63, 0xd1, 0x62, 0xb8, 0xc6, 0xc6, 0x78,
	0x47, 0x8d, 0xd1, 0x5e, 0xdc, 0x18, 0xb4, 0xc9, 0x1f, 0xa3, 0x7b, 0xaa, 0xea, 0xde, 0x91, 0x43,
	0x12, 0x5c, 0xf3, 0x57, 0x70, 0x1d, 0xa3, 0x30, 0x64, 0xfa, 0x33, 0x46, 0xa3, 0xf3, 0x89, 0x77,
	0x5b, 0x18, 0x89, 0xff, 0x1f, 0x39, 0xa9, 0xc6, 0x3e, 0x0c, 0x36, 0xb6, 0x4e, 0xf4, 0x95, 0x41,
	0xb9, 0x16, 0x5b, 0x89, 0x1f, 0x00, 0xc3, 0x23, 0xaf, 0xb2, 0x7f, 0x78, 0x28, 0xf5, 0x8d, 0x1a,
	0x57, 0x81, 0x96, 0x1d, 0x7b, 0xc3, 0xd4, 0x6b, 0x20, 0x45, 0xa2, 0x45, 0x1f, 0xc1, 0xf9, 0x01,
	0x06, 0xaf, 0xc6, 0xae, 0xee, 0x13, 0x7e, 0x84, 0xd0, 0x19, 0xcb, 0xf4, 0xe3, 0x07, 0x31, 0x2d,
	0xee, 0x7f, 0x2b, 0xf2, 0x2d, 0xd8, 0x44, 0xe8, 0x51, 0x32, 0xb1, 0x6d, 0x69, 0x5a, 0x98, 0xbf,
	0x84, 0x5b, 0x84, 0x5f, 0xdd, 0xc0, 0x06, 0x18, 0x25, 0x93, 0x63, 0x12, 0x2c, 0xfb, 0x66, 0x0a,
	0xfe, 0x3f, 0x53, 0x13, 0x3c, 0x17, 0x1b, 0x1c, 0x4f, 0xc1, 0xda, 0xe1, 0xdf, 0xa2, 0x76, 0xb8,
	0x36, 0x37, 0x81, 0x1a, 0xcf, 0x19, 0xa2, 0x5c, 0x18, 0x52, 0x9c, 0xf6, 0xca, 0x38, 0x93, 0xf9,
	0xf7, 0x22, 0xeb, 0x27, 0x4a, 0x09, 0xad, 0x16, 0x1a, 0x7e, 0x81, 0xa5, 0x51, 0xe3, 0x8a, 0x25,
	0x87, 0x55, 0xa3, 0xd8, 0x25, 0xd9, 0x3a, 0xec, 0xe9, 0xf8, 0x11, 0xac, 0xe2, 0x11, 0x2a, 0x3d,
	0xcf, 0xfa, 0xb9, 0x1c, 0x2e, 0xf2, 0x77, 0x46, 0xdc, 0xfa, 0xa7, 0x88, 0xbb, 0x6b, 0xda, 0xd4,
	0x83, 0xaa, 0xde, 0x6d, 0x98, 0x40, 0x55, 0x8e, 0x19, 0x53, 0x8d, 0x99, 0x82, 0xff, 0x14, 0x98,
	0x0c, 0xea, 0xfc, 0x83, 0xc8, 0x6c, 0x75, 0x11, 0xe6, 0xcc, 0x69, 0xce, 0x33, 0xdb, 0x9c, 0xba,
	0x6c, 0x4e, 0x9d, 0x3b, 0x54, 0x6b, 0xb8, 0x54, 0x9b, 0xdd, 0x14, 0x4d, 0xe7, 0xa6, 0x28, 0x63,
	0x6c, 0x39, 0x31, 0x22, 0xfb, 0xa6, 0xa3, 0xd3, 0xfc, 0xd2, 0x0e, 0x3f, 0x2b, 0x21, 0x82, 0xce,
	0x75, 0x72, 0x49, 0xb7, 0x5a, 0x33, 0x36, 0x02, 0xbb, 0x0e, 0x8d, 0x33, 0x21, 0xe8, 0x52, 0x6b,
	0xc6, 0xb8, 0x2c, 0x6b, 0x5a, 0x75, 0x7d, 0xee, 0x76, 0xff, 0xca, 0xd4, 0xd4, 0xd8, 0xfd, 0xa5,
	0x26, 0xb2, 0x7e, 0xd5, 0x5d, 0xbf, 0xf8, 0x53, 0x5b, 0x71, 0x1f, 0x67, 0xd9, 0xa8, 0xfa, 0x39,
	0x40, 0x46, 0x17, 0xa7, 0x56, 0xee, 0x96, 0xff, 0x20, 0xbb, 0xdb, 0xb0, 0x42, 0x47, 0xdb, 0x1b,
	0xb4, 0x4d, 0xf6, 0xae, 0xca, 0x89, 0xb3, 0xe3, 0xe5, 0x7f, 0x3e, 0xd3, 0x4f, 0x61, 0xcb, 0x89,
	0xbc, 0x12, 0xcb, 0x5c, 0xba, 0x7f, 0x0c, 0xd0, 0xdc, 0x10, 0x5c, 0x0c, 0xff, 0xfd, 0xd0, 0x35,
	0x3e, 0x93, 0x5a, 0xe6, 0x99, 0x84, 0xeb, 0xd2, 0x29, 0x8c, 0x79, 0x75, 0x51, 0x17, 0x74, 0x68,
	0xc3, 0xe9, 0x82, 0x67, 0x70, 0xbb, 0x6c, 0xa4, 0x79, 0x97, 0xab, 0x11, 0xbe, 0xf8, 0x1d, 0xa0,
	0x73, 0x28, 0x85, 0xd0, 0x42, 0xb2, 0x57, 0xb0, 0x76, 0x28, 0x34, 0x4d, 0xff, 0xbd, 0xe9, 0xf1,
	0xd5, 0x88, 0xdd, 0x2b, 0x7b, 0x75, 0xc1, 0x53, 0x25, 0xba, 0xe9, 0xec, 0x16, 0xef, 0x0d, 0x5e,
	0x63, 0xfb, 0xb0, 0x3e, 0x43, 0xa1, 0x31, 0x1e, 0x2d, 0x86, 0xc1, 0xf3, 0x97, 0x81, 0x7c, 0x09,
	0x80, 0x20, 0x96, 0x98, 0x9b, 0x3e, 0x80, 0xd1, 0x46, 0xae, 0xb6, 0x7c, 0x6f, 0xf1, 0x1a, 0xfb,
	0x1c, 0x56, 0x0f, 0x85, 0xee, 0x4d, 0xd4, 0xde, 0x14, 0x9f, 0xea, 0x6c, 0xc3, 0xfb, 0x5a, 0x4f,
	0xfc, 0x0f, 0x8b, 0x77, 0x04, 0xaf, 0xb1, 0x97, 0xb0, 0x42, 0x1f, 0x5a, 0xb7, 0x6f, 0x57, 0xbe,
	0x2b, 0x7d, 0x76, 0x1f, 0x19, 0xbc, 0xc6, 0x0e, 0x61, 0xe3, 0x44, 0x64, 0xc3, 0x9e, 0x93, 0xe9,
	0xd0, 0xff, 0x74, 0xb6, 0x13, 0x85, 0x9e, 0xd3, 0xce, 0x0e, 0xaf, 0xb1, 0x5d, 0xb8, 0x71, 0x28,
	0xb4, 0xfd, 0x79, 0x41, 0x2f, 0x81, 0x5d, 0xcd, 0x98, 0x07, 0x45, 0x4c, 0x89, 0xb6, 0xe6, 0x02,
	0x30, 0x8f, 0x98, 0x1a, 0x7b, 0x0d, 0xeb, 0x27, 0x42, 0xbf, 0xc1, 0xdc, 0xdb, 0xdc, 0xdd, 0xf1,
	0xbe, 0x77, 0x67, 0x66, 0x14, 0xf9, 0xb9, 0x77, 0xf7, 0x78, 0x8d, 0xbd, 0x83, 0xeb, 0x27, 0x42,
	0x7f, 0x4d, 0x63, 0xb6, 0x00, 0xbb, 0xeb, 0x81, 0xf9, 0x23, 0x38, 0xba, 0xe7, 0xc3, 0xf9, 0xbb,
	0x44, 0x0c, 0xd8, 0xa7, 0x9b, 0x8d, 0xaa, 0xe2, 0xa7, 0xc8, 0x99, 0xc5, 0xd1, 0x1d, 0x1f, 0xc7,
	0x1d, 0xdd, 0x35, 0xd6, 0xa3, 0x1c, 0xbd, 0x4d, 0x26, 0x44, 0x30, 0x33, 0x3a, 0xd9, 0x7d, 0x0f,
	0xab, 0x3a, 0x77, 0xa3, 0x07, 0x3e, 0xe0, 0xdc, 0xc0, 0xae, 0xb1, 0x23, 0x62, 0x3e, 0xfa, 0xb5,
	0x37, 0xa5, 0xd7, 0x96, 0x9f, 0x35, 0x77, 0xd4, 0x56, 0xb3, 0xe6, 0xee, 0xf1, 0x1a, 0x7b, 0x03,
	0x1b, 0x87, 0x42, 0x1f, 0x38, 0x43, 0xb2, 0x42, 0x7f, 0x6f, 0xc8, 0x46, 0x77, 0x7d, 0x30, 0x6f,
	0x93, 0xda, 0xa0, 0x83, 0x3f, 0xa3, 0xde, 0xc9, 0x21, 0xbb, 0xe5, 0xa1, 0x14, 0x63, 0xb2, 0x42,
	0x85, 0x52, 0xcf, 0x6b, 0xec, 0x15, 0x74, 0xdf, 0xa6, 0x99, 0xee, 0xe1, 0x45, 0x57, 0x89, 0xc7,
	0x1d, 0x33, 0xd5, 0x78, 0xdc, 0x3d, 0x43, 0x28, 0x53, 0xb4, 0xfd, 0x3c, 0xd3, 0x32, 0x19, 0xe8,
	0xbf, 0x0f, 0x65, 0x52, 0x63, 0xa9, 0x64, 0xdc, 0x8a, 0x16, 0x60, 0x15, 0x74, 0xba, 0xbb, 0x08,
	0x6c, 0xc6, 0xa6, 0x63, 0xe8, 0x52, 0xd7, 0x11, 0xce, 0x83, 0x05, 0x38, 0x6e, 0xd7, 0x3d, 0x5c,
	0x84, 0xe5, 0x37, 0xdf, 0xb7, 0x70, 0x0b, 0xf1, 0x4e, 0xe8, 0xda, 0x74, 0x7b, 0xf9, 0xe1, 0x5c,
	0xe2, 0xfd, 0x6b, 0x35, 0xda, 0x9e, 0x2f, 0x81, 0x6f, 0xc1, 0x6b, 0xa7, 0x6d, 0xfa, 0x7f, 0xc3,
	0x67, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x77, 0x9b, 0x44, 0x00, 0x80, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	GetBlockByNum(ctx context.Context, in *ReqBlockByNumber, opts ...grpc.CallOption) (*RespBlock, error)
	GetBlockByHash(ctx context.Context, in *ReqBlockByHash, opts ...grpc.CallOption) (*RespBlock, error)
	GetBalance(ctx context.Context, in *ReqBalance, opts ...grpc.CallOption) (*ResBalance, error)
	GetTxsByAddr(ctx context.Context, in *ReqTx, opts ...grpc.CallOption) (*ResposeTxs, error)
	GetTxByHash(ctx context.Context, in *ReqTxByHash, opts ...grpc.CallOption) (*Tx, error)
	SendTransaction(ctx context.Context, in *ReqTransaction, opts ...grpc.CallOption) (*ResTransaction, error)
	GetAddressNonceAt(ctx context.Context, in *ReqNonce, opts ...grpc.CallOption) (*ResposeNonce, error)
	SetLockBalance(ctx context.Context, in *ReqLockBalance, opts ...grpc.CallOption) (*RespLockBalance, error)
	SetUnlockBalance(ctx context.Context, in *ReqUnlockBalance, opts ...grpc.CallOption) (*RespUnlockBalance, error)
	CreateAddr(ctx context.Context, in *ReqCreateAddr, opts ...grpc.CallOption) (*RespCreateAddr, error)
	GetMaxBlockNumber(ctx context.Context, in *ReqMaxBlockNumber, opts ...grpc.CallOption) (*RespMaxBlockNumber, error)
	GetAddrByPriv(ctx context.Context, in *ReqAddrByPriv, opts ...grpc.CallOption) (*RespAddrByPriv, error)
	GetFrozenAssets(ctx context.Context, in *ReqFrozenAssets, opts ...grpc.CallOption) (*RespFrozenAssets, error)
	SignOrd(ctx context.Context, in *ReqSignOrd, opts ...grpc.CallOption) (*RespSignOrd, error)
	MintToken(ctx context.Context, in *ReqTokenCreate, opts ...grpc.CallOption) (*RespTokenCreate, error)
	CreateContract(ctx context.Context, in *ReqTokenCreate, opts ...grpc.CallOption) (*RespTokenCreate, error)
	GetBalanceToken(ctx context.Context, in *ReqTokenBalance, opts ...grpc.CallOption) (*RespTokenBalance, error)
	SendToken(ctx context.Context, in *ReqTokenTransaction, opts ...grpc.CallOption) (*RespTokenTransaction, error)
	SendSignedTransaction(ctx context.Context, in *ReqSignedTransaction, opts ...grpc.CallOption) (*RespSignedTransaction, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetBlockByNum(ctx context.Context, in *ReqBlockByNumber, opts ...grpc.CallOption) (*RespBlock, error) {
	out := new(RespBlock)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetBlockByNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetBlockByHash(ctx context.Context, in *ReqBlockByHash, opts ...grpc.CallOption) (*RespBlock, error) {
	out := new(RespBlock)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetBlockByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetBalance(ctx context.Context, in *ReqBalance, opts ...grpc.CallOption) (*ResBalance, error) {
	out := new(ResBalance)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetTxsByAddr(ctx context.Context, in *ReqTx, opts ...grpc.CallOption) (*ResposeTxs, error) {
	out := new(ResposeTxs)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetTxsByAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetTxByHash(ctx context.Context, in *ReqTxByHash, opts ...grpc.CallOption) (*Tx, error) {
	out := new(Tx)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetTxByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SendTransaction(ctx context.Context, in *ReqTransaction, opts ...grpc.CallOption) (*ResTransaction, error) {
	out := new(ResTransaction)
	err := c.cc.Invoke(ctx, "/message.Greeter/SendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetAddressNonceAt(ctx context.Context, in *ReqNonce, opts ...grpc.CallOption) (*ResposeNonce, error) {
	out := new(ResposeNonce)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetAddressNonceAt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SetLockBalance(ctx context.Context, in *ReqLockBalance, opts ...grpc.CallOption) (*RespLockBalance, error) {
	out := new(RespLockBalance)
	err := c.cc.Invoke(ctx, "/message.Greeter/SetLockBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SetUnlockBalance(ctx context.Context, in *ReqUnlockBalance, opts ...grpc.CallOption) (*RespUnlockBalance, error) {
	out := new(RespUnlockBalance)
	err := c.cc.Invoke(ctx, "/message.Greeter/SetUnlockBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) CreateAddr(ctx context.Context, in *ReqCreateAddr, opts ...grpc.CallOption) (*RespCreateAddr, error) {
	out := new(RespCreateAddr)
	err := c.cc.Invoke(ctx, "/message.Greeter/CreateAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetMaxBlockNumber(ctx context.Context, in *ReqMaxBlockNumber, opts ...grpc.CallOption) (*RespMaxBlockNumber, error) {
	out := new(RespMaxBlockNumber)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetMaxBlockNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetAddrByPriv(ctx context.Context, in *ReqAddrByPriv, opts ...grpc.CallOption) (*RespAddrByPriv, error) {
	out := new(RespAddrByPriv)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetAddrByPriv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetFrozenAssets(ctx context.Context, in *ReqFrozenAssets, opts ...grpc.CallOption) (*RespFrozenAssets, error) {
	out := new(RespFrozenAssets)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetFrozenAssets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SignOrd(ctx context.Context, in *ReqSignOrd, opts ...grpc.CallOption) (*RespSignOrd, error) {
	out := new(RespSignOrd)
	err := c.cc.Invoke(ctx, "/message.Greeter/SignOrd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) MintToken(ctx context.Context, in *ReqTokenCreate, opts ...grpc.CallOption) (*RespTokenCreate, error) {
	out := new(RespTokenCreate)
	err := c.cc.Invoke(ctx, "/message.Greeter/MintToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) CreateContract(ctx context.Context, in *ReqTokenCreate, opts ...grpc.CallOption) (*RespTokenCreate, error) {
	out := new(RespTokenCreate)
	err := c.cc.Invoke(ctx, "/message.Greeter/CreateContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetBalanceToken(ctx context.Context, in *ReqTokenBalance, opts ...grpc.CallOption) (*RespTokenBalance, error) {
	out := new(RespTokenBalance)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetBalanceToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SendToken(ctx context.Context, in *ReqTokenTransaction, opts ...grpc.CallOption) (*RespTokenTransaction, error) {
	out := new(RespTokenTransaction)
	err := c.cc.Invoke(ctx, "/message.Greeter/SendToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SendSignedTransaction(ctx context.Context, in *ReqSignedTransaction, opts ...grpc.CallOption) (*RespSignedTransaction, error) {
	out := new(RespSignedTransaction)
	err := c.cc.Invoke(ctx, "/message.Greeter/SendSignedTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	GetBlockByNum(context.Context, *ReqBlockByNumber) (*RespBlock, error)
	GetBlockByHash(context.Context, *ReqBlockByHash) (*RespBlock, error)
	GetBalance(context.Context, *ReqBalance) (*ResBalance, error)
	GetTxsByAddr(context.Context, *ReqTx) (*ResposeTxs, error)
	GetTxByHash(context.Context, *ReqTxByHash) (*Tx, error)
	SendTransaction(context.Context, *ReqTransaction) (*ResTransaction, error)
	GetAddressNonceAt(context.Context, *ReqNonce) (*ResposeNonce, error)
	SetLockBalance(context.Context, *ReqLockBalance) (*RespLockBalance, error)
	SetUnlockBalance(context.Context, *ReqUnlockBalance) (*RespUnlockBalance, error)
	CreateAddr(context.Context, *ReqCreateAddr) (*RespCreateAddr, error)
	GetMaxBlockNumber(context.Context, *ReqMaxBlockNumber) (*RespMaxBlockNumber, error)
	GetAddrByPriv(context.Context, *ReqAddrByPriv) (*RespAddrByPriv, error)
	GetFrozenAssets(context.Context, *ReqFrozenAssets) (*RespFrozenAssets, error)
	SignOrd(context.Context, *ReqSignOrd) (*RespSignOrd, error)
	MintToken(context.Context, *ReqTokenCreate) (*RespTokenCreate, error)
	CreateContract(context.Context, *ReqTokenCreate) (*RespTokenCreate, error)
	GetBalanceToken(context.Context, *ReqTokenBalance) (*RespTokenBalance, error)
	SendToken(context.Context, *ReqTokenTransaction) (*RespTokenTransaction, error)
	SendSignedTransaction(context.Context, *ReqSignedTransaction) (*RespSignedTransaction, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) GetBlockByNum(ctx context.Context, req *ReqBlockByNumber) (*RespBlock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockByNum not implemented")
}
func (*UnimplementedGreeterServer) GetBlockByHash(ctx context.Context, req *ReqBlockByHash) (*RespBlock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockByHash not implemented")
}
func (*UnimplementedGreeterServer) GetBalance(ctx context.Context, req *ReqBalance) (*ResBalance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (*UnimplementedGreeterServer) GetTxsByAddr(ctx context.Context, req *ReqTx) (*ResposeTxs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxsByAddr not implemented")
}
func (*UnimplementedGreeterServer) GetTxByHash(ctx context.Context, req *ReqTxByHash) (*Tx, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxByHash not implemented")
}
func (*UnimplementedGreeterServer) SendTransaction(ctx context.Context, req *ReqTransaction) (*ResTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransaction not implemented")
}
func (*UnimplementedGreeterServer) GetAddressNonceAt(ctx context.Context, req *ReqNonce) (*ResposeNonce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressNonceAt not implemented")
}
func (*UnimplementedGreeterServer) SetLockBalance(ctx context.Context, req *ReqLockBalance) (*RespLockBalance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLockBalance not implemented")
}
func (*UnimplementedGreeterServer) SetUnlockBalance(ctx context.Context, req *ReqUnlockBalance) (*RespUnlockBalance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUnlockBalance not implemented")
}
func (*UnimplementedGreeterServer) CreateAddr(ctx context.Context, req *ReqCreateAddr) (*RespCreateAddr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAddr not implemented")
}
func (*UnimplementedGreeterServer) GetMaxBlockNumber(ctx context.Context, req *ReqMaxBlockNumber) (*RespMaxBlockNumber, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMaxBlockNumber not implemented")
}
func (*UnimplementedGreeterServer) GetAddrByPriv(ctx context.Context, req *ReqAddrByPriv) (*RespAddrByPriv, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddrByPriv not implemented")
}
func (*UnimplementedGreeterServer) GetFrozenAssets(ctx context.Context, req *ReqFrozenAssets) (*RespFrozenAssets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFrozenAssets not implemented")
}
func (*UnimplementedGreeterServer) SignOrd(ctx context.Context, req *ReqSignOrd) (*RespSignOrd, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignOrd not implemented")
}
func (*UnimplementedGreeterServer) MintToken(ctx context.Context, req *ReqTokenCreate) (*RespTokenCreate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintToken not implemented")
}
func (*UnimplementedGreeterServer) CreateContract(ctx context.Context, req *ReqTokenCreate) (*RespTokenCreate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContract not implemented")
}
func (*UnimplementedGreeterServer) GetBalanceToken(ctx context.Context, req *ReqTokenBalance) (*RespTokenBalance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalanceToken not implemented")
}
func (*UnimplementedGreeterServer) SendToken(ctx context.Context, req *ReqTokenTransaction) (*RespTokenTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToken not implemented")
}
func (*UnimplementedGreeterServer) SendSignedTransaction(ctx context.Context, req *ReqSignedTransaction) (*RespSignedTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSignedTransaction not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetBlockByNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBlockByNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetBlockByNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBlockByNum(ctx, req.(*ReqBlockByNumber))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetBlockByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBlockByHash(ctx, req.(*ReqBlockByHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBalance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBalance(ctx, req.(*ReqBalance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetTxsByAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetTxsByAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetTxsByAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetTxsByAddr(ctx, req.(*ReqTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetTxByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTxByHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetTxByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetTxByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetTxByHash(ctx, req.(*ReqTxByHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SendTransaction(ctx, req.(*ReqTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetAddressNonceAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNonce)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetAddressNonceAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetAddressNonceAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetAddressNonceAt(ctx, req.(*ReqNonce))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SetLockBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqLockBalance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SetLockBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/SetLockBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SetLockBalance(ctx, req.(*ReqLockBalance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SetUnlockBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqUnlockBalance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SetUnlockBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/SetUnlockBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SetUnlockBalance(ctx, req.(*ReqUnlockBalance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_CreateAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCreateAddr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).CreateAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/CreateAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).CreateAddr(ctx, req.(*ReqCreateAddr))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetMaxBlockNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMaxBlockNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetMaxBlockNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetMaxBlockNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetMaxBlockNumber(ctx, req.(*ReqMaxBlockNumber))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetAddrByPriv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqAddrByPriv)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetAddrByPriv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetAddrByPriv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetAddrByPriv(ctx, req.(*ReqAddrByPriv))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetFrozenAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqFrozenAssets)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetFrozenAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetFrozenAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetFrozenAssets(ctx, req.(*ReqFrozenAssets))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SignOrd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSignOrd)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SignOrd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/SignOrd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SignOrd(ctx, req.(*ReqSignOrd))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_MintToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTokenCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).MintToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/MintToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).MintToken(ctx, req.(*ReqTokenCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_CreateContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTokenCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).CreateContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/CreateContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).CreateContract(ctx, req.(*ReqTokenCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetBalanceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTokenBalance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBalanceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetBalanceToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBalanceToken(ctx, req.(*ReqTokenBalance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SendToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTokenTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SendToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/SendToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SendToken(ctx, req.(*ReqTokenTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SendSignedTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSignedTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SendSignedTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/SendSignedTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SendSignedTransaction(ctx, req.(*ReqSignedTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockByNum",
			Handler:    _Greeter_GetBlockByNum_Handler,
		},
		{
			MethodName: "GetBlockByHash",
			Handler:    _Greeter_GetBlockByHash_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _Greeter_GetBalance_Handler,
		},
		{
			MethodName: "GetTxsByAddr",
			Handler:    _Greeter_GetTxsByAddr_Handler,
		},
		{
			MethodName: "GetTxByHash",
			Handler:    _Greeter_GetTxByHash_Handler,
		},
		{
			MethodName: "SendTransaction",
			Handler:    _Greeter_SendTransaction_Handler,
		},
		{
			MethodName: "GetAddressNonceAt",
			Handler:    _Greeter_GetAddressNonceAt_Handler,
		},
		{
			MethodName: "SetLockBalance",
			Handler:    _Greeter_SetLockBalance_Handler,
		},
		{
			MethodName: "SetUnlockBalance",
			Handler:    _Greeter_SetUnlockBalance_Handler,
		},
		{
			MethodName: "CreateAddr",
			Handler:    _Greeter_CreateAddr_Handler,
		},
		{
			MethodName: "GetMaxBlockNumber",
			Handler:    _Greeter_GetMaxBlockNumber_Handler,
		},
		{
			MethodName: "GetAddrByPriv",
			Handler:    _Greeter_GetAddrByPriv_Handler,
		},
		{
			MethodName: "GetFrozenAssets",
			Handler:    _Greeter_GetFrozenAssets_Handler,
		},
		{
			MethodName: "SignOrd",
			Handler:    _Greeter_SignOrd_Handler,
		},
		{
			MethodName: "MintToken",
			Handler:    _Greeter_MintToken_Handler,
		},
		{
			MethodName: "CreateContract",
			Handler:    _Greeter_CreateContract_Handler,
		},
		{
			MethodName: "GetBalanceToken",
			Handler:    _Greeter_GetBalanceToken_Handler,
		},
		{
			MethodName: "SendToken",
			Handler:    _Greeter_SendToken_Handler,
		},
		{
			MethodName: "SendSignedTransaction",
			Handler:    _Greeter_SendSignedTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
